<a href="https://colab.research.google.com/github/klaropls/MLBootcamp2024/blob/main/MLBootcamp2024_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook contains the code in helping me answer my first homework (01-intro) in ML Bootcamp 2024

In [1]:
import pandas as pd
import numpy as np
from google.colab import files

**Q1. Panda version?**

**Ans. 2.1.4**

In [2]:
pd.__version__

'2.1.4'

We are tasked to get the laptops.csv data from [here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv). I downloaded it and uploaded it in my own MLBootcamp2024 repository.

In [3]:
url = 'https://raw.githubusercontent.com/klaropls/MLBootcamp2024/refs/heads/main/laptops.csv'

We then open it using pandas and print it to get the general picture of the dataframe.

In [4]:
df = pd.read_csv(url)
print(df)


                                                 Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RA

**Q2. Record count?**

This is basically the number of rows of our dataframe. We can readily answer this by getting the shape of df.

**Ans: 2160.**

In [5]:
print(df.shape)

(2160, 12)


**Q3. Laptop brands**

How many laptop brands are presented in the dataset?

From our printed df, the laptop brands are in column 2 (starting from 0). We could simply use the **.nunique()** function.

**Ans. 27**

In [6]:
print(df['Brand'].nunique())

27


**Q4. Missing values**

How many columns in the dataset have missing values?

To answer this, we use the function **.isnull()**. This tells whether the cell has an input or none. For example, if we apply this to a column, it returns a column with binary elements (True/False). Since we know that if there is either an element missing (False) or none (True), we could simply get the number of unique elements per column.

If a column has a missing element, the **.nunique** function will return 2. If none, it will return 1. We could then construct a for loop to get the number of unique elements per column and extract the index of elements equal to 2 (or =/= 1).

**Ans. 3**

In [7]:
misscol = []

for i in range(12):
    a = df.iloc[:, i].isnull().nunique()
    misscol.append(a)

print(misscol)

[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1]


In [8]:
indices = [index for index, value in enumerate(misscol) if value != 1]

In [9]:
print(indices)

[7, 8, 9]


In [10]:
print(len(indices))

3


**Q5. Maximum final price**

What's the maximum final price of Dell notebooks in the dataset?

We first filter the dataframe by a simple indexing. Afterwards, we use the **.max()** function to find the max value in the filtered column.

In [11]:
column_names = df.columns[0:12].tolist()
print (column_names)

['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage', 'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price']


In [12]:
onlydell_df = df[df['Brand'] == 'Dell']

In [13]:
print(onlydell_df['Final Price'].max())

3936.0


Q6. Median value of Screen

    Find the median value of Screen column in the dataset.
    Next, calculate the most frequent value of the same Screen column.
    Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
    Now, calculate the median value of Screen once again.

Has it changed? **Ans. No**

    Hint: refer to existing mode and median functions to complete the task.

    Yes
    No


In [14]:
median = df['Screen'].median()
mode = df['Screen'].mode()

print(mode)


0    15.6
Name: Screen, dtype: float64


In [15]:
filled_screen = df['Screen'].fillna(mode)

In [16]:
print(filled_screen.median())

15.6


I am actually quite surprised with the answer. My hunch is that there are very minimal blank missing entries from the screen column. Let us check this by doing the following:

In [17]:
missing_count = df['Screen'].isnull().sum()

print(missing_count)

4


Ok, this makes sense. Only 4 missing entries over 2k+. I should then not expect the median to change.

Q7. Sum of weights

    Select all the "Innjoo" laptops from the dataset.
    Select only columns RAM, Storage, Screen.
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Compute the inverse of XTX.
    Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the sum of all the elements of the result?


In [18]:
onlyinnjoo_df = df[df['Brand'] == 'Innjoo']

In [19]:
column_names2 = onlyinnjoo_df.columns[0:12].tolist()
print (column_names)

['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage', 'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price']


In [20]:
onlyinjoo_subset = onlyinnjoo_df[['RAM', 'Storage', 'Screen']]
print(onlyinjoo_subset)

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1


In [21]:
print(len(onlyinjoo_subset))

6


In [22]:
X = onlyinjoo_subset.values

In [23]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [24]:
XTX = np.dot(X.T,X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [25]:
XTX_inv = np.linalg.inv(XTX)

In [26]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [27]:
w= np.dot(np.dot(XTX_inv,X.T),y)

In [28]:
print(w)
print(w.sum())

[45.58076606  0.42783519 45.29127938]
91.2998806299555
